---
codesearch_volume_device: /dev/sdb
codesearch_domain: codesearch.archlinux.org
codesearch_repos: "core extra"
codesearch_user: codesearch
codesearch_group: codesearch

codesearch_index_name: "Arch Linux Packages"
codesearch_extract_schedule: "*-*-* 02:30:00"

codesearch_zoekt_version: "latest"
codesearch_zoekt_web_port: 6070
codesearch_index_parallelism: 4
codesearch_index_concurrent: 1

codesearch_ftp_dir: /srv/ftp
codesearch_sources_dir: /srv/codesearch/sources
codesearch_index_dir: /srv/codesearch/index
codesearch_shards_dir: /srv/codesearch/shards
codesearch_state_dir: /srv/codesearch/state
codesearch_fetch_workdir: /var/lib/codesearch/fetch-work
codesearch_log_dir: /var/log/codesearch

codesearch_gitlab_base: "https://gitlab.archlinux.org/archlinux/packaging/packages"
codesearch_gitlab_token: "{{ vault_codesearch_gitlab_token }}"
codesearch_fetch_jobs: 2
codesearch_cleanup_sources: true
