#!/usr/bin/python

import os
from pathlib import Path

import requests

data = requests.get("http://169.254.169.254/2009-04-04/meta-data/public-keys")
data.raise_for_status()

path = Path("/root/.ssh/authorized_keys")
path.parent.mkdir(mode=0o700, exist_ok=True)
os.chmod(path.parent, 0o700)

with open(path, "w") as file:
    for key in data.json():
        file.write(f"{key}\n")
os.chmod(path, 0o600)
