{
 "title": "Borg Backups",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "Disk Usage (Hetzner)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "10000*2^30", "legendFormat": "Quota" },
    {
     "expr": "hetzner_storage_box_used_bytes{instance=\"monitoring.archlinux.org\"}",
     "legendFormat": "Backups"
    },
    {
     "expr": "10000*2^30 - hetzner_storage_box_size_bytes{instance=\"monitoring.archlinux.org\"}",
     "legendFormat": "Snapshots"
    },
    {
     "expr": "10000*2^30 - hetzner_storage_box_free_bytes{instance=\"monitoring.archlinux.org\"}",
     "legendFormat": "Total Used"
    }
   ]
  },
  {
   "title": "Free Space (Hetzner)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hetzner_storage_box_free_bytes{instance=\"monitoring.archlinux.org\"}"
    }
   ]
  },
  {
   "title": "Borg Repository Size (Hetzner)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "borg_hetzner_repo_size_bytes{}", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Borg Repository Size (Offsite)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "borg_offsite_repo_size_bytes{}", "legendFormat": "{{ instance }}" }
   ]
  }
 ]
}