{
 "title": "debuginfod",
 "description": "Debuginfod server: https://debuginfod.archlinux.org/ - Packages indexed: https://debuginfod.archlinux.org/packages/",
 "tags": [ "debuginfod" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": "debuginfod.archlinux.org" }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ready{instance=\"debuginfod.archlinux.org\"}"
    }
   ]
  },
  {
   "title": "HTTP Queries (200)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_responses_transfer_bytes_count{instance=~\"$instance\",code=\"200\"}[2m])",
     "legendFormat": "{{code}} - {{type}}"
    }
   ]
  },
  {
   "title": "Response Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(http_responses_transfer_bytes_sum{instance=~\"$instance\"}[2m])",
     "legendFormat": "{{code}} - {{type}}"
    }
   ]
  },
  {
   "title": "Debuginfos",
   "type": "stat",
   "description": "Number of unique debug symbol files found in packages",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "found_debuginfo_total" }
   ]
  },
  {
   "title": "Sourcerefs",
   "type": "stat",
   "description": "Source References is the number of source files that has been indexed by debuginfod",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "found_sourcerefs_total" }
   ]
  },
  {
   "title": "Requested",
   "type": "stat",
   "description": "Number of requested debuginfo files",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_responses_transfer_bytes_count{instance=~\"$instance\",code=\"200\",type=\"debuginfo\"}"
    }
   ]
  },
  {
   "title": "Requested",
   "type": "stat",
   "description": "Number of requested source files",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_responses_transfer_bytes_count{instance=~\"$instance\",code=\"200\",type=\"source\"}"
    }
   ]
  },
  {
   "title": "Thread State",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "thread_busy{instance=\"debuginfod.archlinux.org\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Watched error_count which only exists with recorded errors",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(error_count{instance=~\"$instance\"}[2m])",
     "legendFormat": "{{libc}}{{libarchive}}"
    }
   ]
  },
  {
   "title": "scanning throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(scanned_bytes_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "HTTP Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(http_responses_duration_milliseconds_sum{instance=\"debuginfod.archlinux.org\",code=\"200\",job=\"debuginfod\"}[2m])/rate(http_responses_duration_milliseconds_count{instance=\"debuginfod.archlinux.org\",code=\"200\",job=\"debuginfod\"}[2m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "corpus size ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "groom{statistic=~\"files scanned.*mb.*\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{statistic}}"
    },
    {
     "expr": "groom{statistic=~\"files scanned.*#.*\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{statistic}}"
    }
   ]
  },
  {
   "title": "response avg time",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 17 },
   "targets": [
    {
     "expr": "rate(http_responses_duration_milliseconds_sum{instance=~\"$instance\"}[2m])/rate(http_responses_duration_milliseconds_count{instance=~\"$instance\"}[2m])"
    }
   ]
  },
  {
   "title": "sqlite3 avg time",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "rate(sqlite3_milliseconds_sum{instance=~\"$instance\"}[2m])/rate(sqlite3_milliseconds_count{instance=~\"$instance\"}[2m])"
    }
   ]
  },
  {
   "title": "data sent per month",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(http_responses_transfer_bytes_sum{code=\"200\",instance=~\"$instance\"}[4w])*60*60*24*7*4)",
     "legendFormat": " {{instance}}"
    }
   ]
  },
  {
   "title": "Available free space",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "filesys_free_ratio{instance=~\"$instance\"}",
     "legendFormat": "{{purpose}}"
    }
   ]
  }
 ]
}