{
 "title": "Geo Mirrors",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "Daily Outgoing Traffic (stacked)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (increase(node_network_transmit_bytes_total{instance=~\".*\\\\.mirror\\\\.pkgbuild\\\\.com\",device=~\"en.*\"}[1d]))",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{instance=~\".*\\\\.mirror\\\\.pkgbuild\\\\.com\",device=~\"en.*\"}[1d]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Outgoing Traffic (stacked, 30 day rolling period)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (increase(node_network_transmit_bytes_total{instance=~\".*\\\\.mirror\\\\.pkgbuild\\\\.com\",device=~\"en.*\"}[30d]))",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{instance=~\".*\\\\.mirror\\\\.pkgbuild\\\\.com\",device=~\"en.*\"}[30d]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DNS Queries",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(pdns_auth_udp_queries{instance=~\".*\\\\.mirror\\\\.pkgbuild\\\\.com\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}