{
 "title": "Gitlab metrics",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  { "title": "Trends", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total groups",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "gitlab_exporter_trends_total_groups ",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Total projects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "gitlab_exporter_trends_total_projects",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Total users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "gitlab_exporter_trends_total_users",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Total commit count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "gitlab_exporter_total_commit_count",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Total Sizes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total storage size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gitlab_exporter_total_storage_size",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Total build artifacts size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gitlab_exporter_total_build_artifacts_size",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Total LFS objects size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gitlab_exporter_total_lfs_objects_size",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Total package size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gitlab_exporter_total_packages_size",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Total pipeline artifacts size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gitlab_exporter_total_pipeline_artifacts_size",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Total repository size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gitlab_exporter_total_repository_size",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Total uploads size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gitlab_exporter_total_uploads_size",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Total snippets size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gitlab_exporter_total_snippets_size",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Total wiki size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gitlab_exporter_total_wiki_size",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Top 15 Sizes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Storage Sizes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(fullname) (gitlab_exporter_top_storage_sizes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Artifact Sizes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(fullname) (gitlab_exporter_top_build_artifacts_sizes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Repository Sizes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(fullname) (gitlab_exporter_top_repository_sizes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipeline Artifacts Sizes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(fullname) (gitlab_exporter_top_pipeline_artifacts_sizes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Snippets Sizes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(fullname) (gitlab_exporter_top_snippets_sizes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packages Sizes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(fullname) (gitlab_exporter_top_packages_sizes)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}