{
 "title": "goaurrpc",
 "description": "/rpc metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Stats (last 24 hours)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rpc_data_last_refresh * 1000", "legendFormat": "Last metadata refresh" },
    {
     "expr": "sum(increase(rpc_requests[24h]))",
     "legendFormat": "Requests served"
    },
    {
     "expr": "sum(increase(rpc_requests_rate_limited[24h]))",
     "legendFormat": "Requests rate-limited"
    },
    { "expr": "increase(rpc_cache_hits[24h])", "legendFormat": "Cache hits" }
   ]
  },
  {
   "title": "Total requests (last 24 hours)",
   "type": "piechart",
   "description": "The number of requests by \"type\" within the last 24 hours",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(type) (increase(rpc_requests[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total search-requests (last 24 hours)",
   "type": "piechart",
   "description": "The number of requests for the search type by \"by\" parameter within the last 24 hours",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(by) (increase(rpc_requests{type=\"search\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"goaurrpc\"}",
     "legendFormat": "HEAP"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"goaurrpc\"}",
     "legendFormat": "RSS"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by(type) (rate(rpc_requests[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Requests rate-limited per second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(rpc_requests_rate_limited[5m])",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Search requests per second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(by) (rate(rpc_requests{type=\"search\"}[5m]))",
     "legendFormat": "{{by}}"
    }
   ]
  },
  {
   "title": "Request processing duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(rpc_request_duration_seconds_bucket[5m])))",
     "legendFormat": "quantile95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(rpc_request_duration_seconds_bucket[5m])))",
     "legendFormat": "quantile50"
    },
    {
     "expr": "rate(rpc_request_duration_seconds_sum[5m]) / rate(rpc_request_duration_seconds_count[5m])",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Response size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(rpc_response_size_bytes_sum[5m])) / sum(rate(rpc_response_size_bytes_count[5m]))",
     "legendFormat": "average"
    }
   ]
  }
 ]
}