{
 "title": "Rebuilderd",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "suite",
    "label": "suite",
    "query": "label_values(rebuilderd_results,suite)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overall status",
   "type": "graph",
   "description": "Overall statistics of all repositories.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rebuilderd_results)",
     "legendFormat": "{{ suite }}"
    }
   ]
  },
  {
   "title": "$suite",
   "type": "graph",
   "description": "rebuilderd results for [$suite] repository",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rebuilderd_results{suite=\"$suite\"}",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Active rebuilderd workers",
   "type": "graph",
   "description": "Number of active rebuidlerd-workers",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rebuilderd_workers", "legendFormat": "active workers" }
   ]
  },
  {
   "title": "Queue length",
   "type": "graph",
   "description": "The rebuilderd queue length of to be rebuild packages",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rebuilderd_queue_length", "legendFormat": "queue length" }
   ]
  }
 ]
}