{
 "title": "S.M.A.R.T. disk monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(smart_device_info, instance)"
    }
   },
   {
    "name": "disk",
    "query": {
     "query": "label_values(smart_device_info, disk)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Unhealthy disks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(smart_device_smart_healthy{instance=~\"$instance\"})-sum(smart_device_smart_healthy{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 21, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(smart_temperature_celsius{ instance=~\"$instance\", disk=~\"$disk\" }) by (instance, disk)",
     "legendFormat": "{{ disk }}"
    }
   ]
  },
  {
   "title": "Self test",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(smart_device_self_test{instance=~\"$instance\"})-sum(smart_device_self_test{instance=~\"$instance\"})"
    }
   ]
  }
 ]
}