archweb_db_host: "{{ hostvars['archlinux.org']['wireguard_address'] }}"

# raise tcp window limits to 32MiB
tcp_rmem: "10240 87380 33554432"
tcp_wmem: "10240 87380 33554432"

nginx_enable_http3: true
nginx_stream: true

ignore_package_upgrades:
  # rsync 3.5.1 causes issues with the rsyncd socket:
  # - https://gitlab.archlinux.org/archlinux/infrastructure/-/work_items/876
  # - https://github.com/RsyncProject/rsync/issues/1119
  - rsync
