ansible_port: 2222
sshd_port: 2222
enable_zram_swap: true
additional_addresses: ["213.133.111.6/32", "2a01:4f8:222:174c::2/64"]
wireguard_address: 10.0.0.5
wireguard_public_key: ebEWzriL3dohjDP49Hp+SGHZBnzx8fjnohDN3igQlCc=
network_interface: "en*"
ipv4_address: "213.133.111.15"
ipv4_netmask: "/32"
ipv6_address: "2a01:4f8:222:174c::1"
ipv6_netmask: "/64"
ipv4_gateway: "213.133.111.1"
ipv6_gateway: "fe80::1"
system_disks:
  - /dev/nvme0n1
  - /dev/nvme1n1
fail2ban_jails:
  sshd: true
  postfix: false
  dovecot: false
  nginx_limit_req: true

anubis_extra_rules:
  - skip-all-non-browser
  - gitlab-upstream-location

gitlab_pages_archlinux_page_map:
  archlinux.page: archlinux-page-caddcd.archlinux.page
  signstar.archlinux.page: signstar-fda89a.archlinux.page
  rfc.archlinux.page: rfcs-12a678.archlinux.page
  repod.archlinux.page: repod-7effd5.archlinux.page
  monthly-reports.archlinux.page: monthly-reports-985740.archlinux.page
  pacman.archlinux.page: pacman-0adb8c.archlinux.page
  alpm.archlinux.page: alpm-29eafc.archlinux.page
  devblog.archlinux.page: devblog-3e312b.archlinux.page
  voa.archlinux.page: voa-f11571.archlinux.page
  manual.archlinux.page: developer-manual-2e40de.archlinux.page
  ports.archlinux.page: docs-4e89b6.archlinux.page

# In order for this to work, you also need to add a CNAME entry.
# This can be done by adding an entry to `archlinux_org_gitlab_pages` in `tf-stage1/archlinux.tf`
gitlab_pages_archlinux_org_map:
  conf.archlinux.org: conf-200b83.archlinux.page
  whatcanidofor.archlinux.org: neoasknot-2533cf.archlinux.page
  openpgpkey.archlinux.org: archlinux-keyring-2139b9.archlinux.page
  openpgpkey.master-key.archlinux.org: archlinux-keyring-2139b9.archlinux.page
  bugs.archlinux.org: bugs-archive-82eed9.archlinux.page
  package-maintainer-bylaws.aur.archlinux.org: package-maintainer-bylaws-f8a287.archlinux.page
  terms.archlinux.org: service-agreements-47fcf9.archlinux.page
  patchwork.archlinux.org: patchwork-archive-153924.archlinux.page
  panic.archlinux.org: panic-report-09f973.archlinux.page

certbot_dns_support: true
certbot_tsig_name: gitlab-pages
