- name: Install sudo
  pacman: name=sudo state=present

- name: Remove all users from wheel group
  ansible.builtin.group: name=wheel state=absent force=true

- name: Re-create the wheel group
  ansible.builtin.group: name=wheel state=present

- name: Add sudo users to wheel
  user: name="{{ item }}" append=yes groups=wheel
  loop: "{{ sudo_users }}"
  tags: ['archusers']

- name: Allow wheel group to use sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel ALL=\(ALL:ALL\) ALL'
    insertafter: '^# %wheel ALL=\(ALL:ALL\) ALL'
    line: '%wheel ALL=(ALL:ALL) ALL'
    validate: 'visudo -cf %s'
    mode: '0440'
    owner: root
    group: root
