- name: Install podman and webhook
  pacman: name=podman,webhook state=present

- name: Create user
  user: >
    name=buildbtw home="{{ buildbtw_dir }}"
    shell=/bin/nologin system=yes createhome=yes

- name: Create ssl cert
  include_role:
    name: certificate
  vars:
    domains: ["{{ buildbtw_domain }}"]

- name: Make nginx log dir
  file: path=/var/log/nginx/{{ buildbtw_domain }} state=directory owner=root group=root mode=0755

- name: Set up nginx
  template: src=nginx.d.conf.j2 dest=/etc/nginx/nginx.d/buildbtw.conf owner=root group=root mode=644
  notify: Reload nginx
  tags: ['nginx']

- name: Enable lingering is needed so that podman can work
  command: loginctl enable-linger buildbtw
  args:
    creates: /var/lib/systemd/linger/buildbtw

- name: Create containers dirs
  file: path=/etc/containers/systemd owner=root group=root mode=0755 state=directory

- name: Install buildbtw systemd container file
  template: src=buildbtw.container.j2 dest=/etc/containers/systemd/buildbtw.container owner=root group=root mode=0644
  notify: Restart buildbtw

- name: Install buildbtw environment config
  template: src=buildbtw.env.j2 dest=/etc/conf.d/buildbtw owner=root group=root mode=0600
  notify: Restart buildbtw

- name: Install webhook config
  copy: src=hooks.json dest=/etc/webhook/hooks.json owner=root group=root mode=0644
  notify: Restart webhook
  when: buildbtw_stage in ["staging", "dev"]

- name: Install deployment scripts
  copy: src={{ item }} dest=/usr/local/bin/{{ item }} owner=root group=root mode=0755
  when: buildbtw_stage in ["staging", "dev"]
  loop:
    - deploy-branch.sh
    - undeploy-branch.sh

- name: Create dir for webhook systemd service override
  file: path=/etc/systemd/system/webhook.service.d owner=root group=root mode=0755 state=directory
  when: buildbtw_stage in ["staging", "dev"]

- name: Make sure webhook runs only on localhost
  copy: src=webhook-override.conf dest=/etc/systemd/system/webhook.service.d/override.conf owner=root group=root mode=644
  notify: Restart webhook
  when: buildbtw_stage in ["staging", "dev"]

- name: Start and enable webhook systemd service
  systemd: name=webhook state=started enabled=true daemon_reload=yes
  when: buildbtw_stage in ["staging", "dev"]

- name: Start and enable buildbtw systemd service
  systemd: name=builbdtw state=started enabled=true daemon_reload=yes
