- name: Install hedgedoc
  pacman: name=hedgedoc state=present

- name: Add hedgedoc postgres db
  postgresql_db: name=hedgedoc
  become: true
  become_user: postgres
  become_method: ansible.builtin.su

- name: Add hedgedoc postgres user
  postgresql_user: login_db=hedgedoc name=hedgedoc password={{ vault_postgres_users.hedgedoc }} encrypted=true
  become: true
  become_user: postgres
  become_method: ansible.builtin.su

- name: Setup nginx configuration
  include_role:
    name: vhost
  vars:
    vhost_domain: "{{ hedgedoc_domain }}"
    vhost_backend: "http://localhost:3000"
    vhost_metrics_token: "{{ vault_hedgedoc_metrics_token }}"
    vhost_paths:
      - path: /status
        block: true

- name: Add hedgedoc.service.d dir
  file: state=directory path=/etc/systemd/system/hedgedoc.service.d owner=root group=root mode=0755

- name: Install hedgedoc.service snippet for configuration
  template: src=hedgedoc.service.d.j2 dest=/etc/systemd/system/hedgedoc.service.d/local.conf owner=root group=root mode=0644

- name: Install hedgedoc config file
  template: src=config.json.j2 dest=/etc/webapps/hedgedoc/config.json owner=root group=hedgedoc mode=0640

- name: Start and enable hedgedoc
  service: name=hedgedoc.service enabled=yes state=started
