wireguard_address: 10.0.0.57
wireguard_public_key: 10qBiWru6O06u/h4ytXl6662e31ycw1w5XE/70LfWRY=
nginx_enable_http3: true
buildbtw_domain: buildbtw.archlinux.builders
buildbtw_stage: staging
buildbtw_image_tag: main
buildbtw_gitlab_packages_group: archlinux/packaging/packages
